

# resource directories
models_dir: "data/models"
training_dir: "data/texts"
unicode_dir: "data/unicode"

# logging, see https://docs.python.org/3/library/logging.config.html#logging-config-fileformat
logging:
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    simpleExample:
      level: DEBUG
      handlers: [console]
      propagate: no
  root:
    level: DEBUG
    handlers: [console]

## CORS setting for the web API
CORS:
  allowed_origins:
    - "*"
  allowed_methods:
    - "OPTIONS"
    - "GET"
    - "PUT"
    - "POST"
    - "DELETE"
    - "HEAD"
  allowed_headers:
    - "X-Requested-With"
    - "Content-Type"
    - "Accept"
    - "Origin"

## web API settings
api:
  port: 8050 
  host: "0.0.0.0"
  # to specify a custom default header in the response
  #header: 
  log_level: "debug"
  reload: false
  # the following is used in the generated API documentation
  version: "0.1"
  name: "OCR scorer web API"
  description: "Web API for the OCR scorer service"
  api_route: ""
